version: '3'
services:
  app:
    build: .
    ports:
      - "1337:1337"
    environment:
      - NODE_ENV=production
      - MONGODB_URI=your_mongodb_uri
      - PARSE_APP_ID=your_app_id
      - PARSE_MASTER_KEY=your_master_key
      - PARSE_SERVER_URL=https://your-domain.com/parse
      - ALCHEMY_API_KEY=your_alchemy_key
      - WALLET_TO_MONITOR=your_wallet_address
      - DASHBOARD_USER=your_dashboard_username
      - DASHBOARD_PASS=your_dashboard_password
    restart: always 